import { MapTile } from './index';

// Map data from the latest API response
export const sampleMapData: MapTile[] = [
	// row 1 - 1 ~ 15
	{ id: 1, axialQ: -6, axialR: -3, landType: "MARINE", isActive: true },
	{ id: 2, axialQ: -5, axialR: -3, landType: "MARINE", isActive: true },
	{ id: 3, axialQ: -4, axialR: -3, landType: "MARINE", isActive: true },
	{ id: 4, axialQ: -3, axialR: -3, landType: "MARINE", isActive: true },
	{ id: 5, axialQ: -2, axialR: -3, landType: "PLAIN", isActive: true },
	{ id: 6, axialQ: -1, axialR: -3, landType: "PLAIN", isActive: true },
	{ id: 7, axialQ: 0, axialR: -3, landType: "PLAIN", isActive: true },
	{ id: 8, axialQ: 1, axialR: -3, landType: "PLAIN", isActive: true },
	{ id: 9, axialQ: 2, axialR: -3, landType: "PLAIN", isActive: true },
	{ id: 10, axialQ: 3, axialR: -3, landType: "PLAIN", isActive: true },
	{ id: 11, axialQ: 4, axialR: -3, landType: "MARINE", isActive: true },
	{ id: 12, axialQ: 5, axialR: -3, landType: "MARINE", isActive: true },
	{ id: 13, axialQ: 6, axialR: -3, landType: "MARINE", isActive: true },
	{ id: 14, axialQ: 7, axialR: -3, landType: "MARINE", isActive: true },
	{ id: 15, axialQ: 8, axialR: -3, landType: "MARINE", isActive: true },
	
	// row 2 - 16 ~ 30
	{ id: 16, axialQ: -6, axialR: -2, landType: "MARINE", isActive: true },
	{ id: 17, axialQ: -5, axialR: -2, landType: "MARINE", isActive: true },
	{ id: 18, axialQ: -4, axialR: -2, landType: "MARINE", isActive: true },
	{ id: 19, axialQ: -3, axialR: -2, landType: "MARINE", isActive: true },
	{ id: 20, axialQ: -2, axialR: -2, landType: "PLAIN", isActive: true },
	{ id: 21, axialQ: -1, axialR: -2, landType: "COASTAL", isActive: true },
	{ id: 22, axialQ: 0, axialR: -2, landType: "COASTAL", isActive: true },
	{ id: 23, axialQ: 1, axialR: -2, landType: "COASTAL", isActive: true },
	{ id: 24, axialQ: 2, axialR: -2, landType: "COASTAL", isActive: true },
	{ id: 25, axialQ: 3, axialR: -2, landType: "PLAIN", isActive: true },
	{ id: 26, axialQ: 4, axialR: -2, landType: "PLAIN", isActive: true },
	{ id: 27, axialQ: 5, axialR: -2, landType: "PLAIN", isActive: true },
	{ id: 28, axialQ: 6, axialR: -2, landType: "MARINE", isActive: true },
	{ id: 29, axialQ: 7, axialR: -2, landType: "MARINE", isActive: true },
	{ id: 30, axialQ: 8, axialR: -2, landType: "MARINE", isActive: true },
	
	// row 3 - 31 ~ 45
	{ id: 31, axialQ: -7, axialR: -1, landType: "MARINE", isActive: true },
	{ id: 32, axialQ: -6, axialR: -1, landType: "MARINE", isActive: true },
	{ id: 33, axialQ: -5, axialR: -1, landType: "MARINE", isActive: true },
	{ id: 34, axialQ: -4, axialR: -1, landType: "MARINE", isActive: true },
	{ id: 35, axialQ: -3, axialR: -1, landType: "PLAIN", isActive: true },
	{ id: 36, axialQ: -2, axialR: -1, landType: "PLAIN", isActive: true },
	{ id: 37, axialQ: -1, axialR: -1, landType: "PLAIN", isActive: true },
	{ id: 38, axialQ: 0, axialR: -1, landType: "PLAIN", isActive: true },
	{ id: 39, axialQ: 1, axialR: -1, landType: "PLAIN", isActive: true },
	{ id: 40, axialQ: 2, axialR: -1, landType: "PLAIN", isActive: true },
	{ id: 41, axialQ: 3, axialR: -1, landType: "COASTAL", isActive: true },
	{ id: 42, axialQ: 4, axialR: -1, landType: "COASTAL", isActive: true },
	{ id: 43, axialQ: 5, axialR: -1, landType: "PLAIN", isActive: true },
	{ id: 44, axialQ: 6, axialR: -1, landType: "PLAIN", isActive: true },
	{ id: 45, axialQ: 7, axialR: -1, landType: "MARINE", isActive: true },

	// row 4 - 46 ~ 60
	{ id: 46, axialQ: -7, axialR: 0, landType: "PLAIN", isActive: true },
	{ id: 47, axialQ: -6, axialR: 0, landType: "PLAIN", isActive: true },
	{ id: 48, axialQ: -5, axialR: 0, landType: "PLAIN", isActive: true },
	{ id: 49, axialQ: -4, axialR: 0, landType: "MARINE", isActive: true },
	{ id: 50, axialQ: -3, axialR: 0, landType: "MARINE", isActive: true },
	{ id: 51, axialQ: -2, axialR: 0, landType: "MARINE", isActive: true },
	{ id: 52, axialQ: -1, axialR: 0, landType: "PLAIN", isActive: true },
	{ id: 53, axialQ: 0, axialR: 0, landType: "MARINE", isActive: true },
	{ id: 54, axialQ: 1, axialR: 0, landType: "MARINE", isActive: true },
	{ id: 55, axialQ: 2, axialR: 0, landType: "PLAIN", isActive: true },
	{ id: 56, axialQ: 3, axialR: 0, landType: "COASTAL", isActive: true },
	{ id: 57, axialQ: 4, axialR: 0, landType: "COASTAL", isActive: true },
	{ id: 58, axialQ: 5, axialR: 0, landType: "COASTAL", isActive: true },
	{ id: 59, axialQ: 6, axialR: 0, landType: "PLAIN", isActive: true },
	{ id: 60, axialQ: 7, axialR: 0, landType: "MARINE", isActive: true },

	// row 5 - 61 ~ 75
	{ id: 61, axialQ: -8, axialR: 1, landType: "PLAIN", isActive: true },
	{ id: 62, axialQ: -7, axialR: 1, landType: "COASTAL", isActive: true },
	{ id: 63, axialQ: -6, axialR: 1, landType: "COASTAL", isActive: true },
	{ id: 64, axialQ: -5, axialR: 1, landType: "PLAIN", isActive: true },
	{ id: 65, axialQ: -4, axialR: 1, landType: "PLAIN", isActive: true },
	{ id: 66, axialQ: -3, axialR: 1, landType: "MARINE", isActive: true },
	{ id: 67, axialQ: -2, axialR: 1, landType: "MARINE", isActive: true },
	{ id: 68, axialQ: -1, axialR: 1, landType: "MARINE", isActive: true },
	{ id: 69, axialQ: 0, axialR: 1, landType: "MARINE", isActive: true },
	{ id: 70, axialQ: 1, axialR: 1, landType: "PLAIN", isActive: true },
	{ id: 71, axialQ: 2, axialR: 1, landType: "COASTAL", isActive: true },
	{ id: 72, axialQ: 3, axialR: 1, landType: "PLAIN", isActive: true },
	{ id: 73, axialQ: 4, axialR: 1, landType: "PLAIN", isActive: true },
	{ id: 74, axialQ: 5, axialR: 1, landType: "PLAIN", isActive: true },
	{ id: 75, axialQ: 6, axialR: 1, landType: "MARINE", isActive: true },

	// row 6 - 76 ~ 90
	{ id: 76, axialQ: -8, axialR: 2, landType: "PLAIN", isActive: true },
	{ id: 77, axialQ: -7, axialR: 2, landType: "COASTAL", isActive: true },
	{ id: 78, axialQ: -6, axialR: 2, landType: "COASTAL", isActive: true },
	{ id: 79, axialQ: -5, axialR: 2, landType: "PLAIN", isActive: true },
	{ id: 80, axialQ: -4, axialR: 2, landType: "PLAIN", isActive: true },
	{ id: 81, axialQ: -3, axialR: 2, landType: "MARINE", isActive: true },
	{ id: 82, axialQ: -2, axialR: 2, landType: "MARINE", isActive: true },
	{ id: 83, axialQ: -1, axialR: 2, landType: "MARINE", isActive: true },
	{ id: 84, axialQ: 0, axialR: 2, landType: "PLAIN", isActive: true },
	{ id: 85, axialQ: 1, axialR: 2, landType: "PLAIN", isActive: true },
	{ id: 86, axialQ: 2, axialR: 2, landType: "PLAIN", isActive: true },
	{ id: 87, axialQ: 3, axialR: 2, landType: "MARINE", isActive: true },
	{ id: 88, axialQ: 4, axialR: 2, landType: "MARINE", isActive: true },
	{ id: 89, axialQ: 5, axialR: 2, landType: "MARINE", isActive: true },
	{ id: 90, axialQ: 6, axialR: 2, landType: "MARINE", isActive: true },

	// row 7 - 91 ~ 105
	{ id: 91, axialQ: -9, axialR: 3, landType: "MARINE", isActive: true },
	{ id: 92, axialQ: -8, axialR: 3, landType: "PLAIN", isActive: true },
	{ id: 93, axialQ: -7, axialR: 3, landType: "PLAIN", isActive: true },
	{ id: 94, axialQ: -6, axialR: 3, landType: "PLAIN", isActive: true },
	{ id: 95, axialQ: -5, axialR: 3, landType: "MARINE", isActive: true },
	{ id: 96, axialQ: -4, axialR: 3, landType: "MARINE", isActive: true },
	{ id: 97, axialQ: -3, axialR: 3, landType: "MARINE", isActive: true },
	{ id: 98, axialQ: -2, axialR: 3, landType: "MARINE", isActive: true },
	{ id: 99, axialQ: -1, axialR: 3, landType: "MARINE", isActive: true },
	{ id: 100, axialQ: 0, axialR: 3, landType: "PLAIN", isActive: true },
	{ id: 101, axialQ: 1, axialR: 3, landType: "MARINE", isActive: true },
	{ id: 102, axialQ: 2, axialR: 3, landType: "MARINE", isActive: true },
	{ id: 103, axialQ: 3, axialR: 3, landType: "MARINE", isActive: true },
	{ id: 104, axialQ: 4, axialR: 3, landType: "MARINE", isActive: true },
	{ id: 105, axialQ: 5, axialR: 3, landType: "MARINE", isActive: true },
]; 